### PR TITLE
add module catalog metadata.md

### PR DESCRIPTION
**Pull request by kavya498**

### CODE REVIEW

**Comment by SirSpidey** [comment]
@kavya498 Sorry for the delay. Didn't get a notification about this. Will look at it today.

**Comment by SirSpidey** [comment]
@kavya498 see https://github.com/kavya498/documentation/pull/1

**Review by SirSpidey — APPROVED** [review]
Thanks for the updates.
Fixed some of my own issues in the markdown syntax.

**Comment by kavya498** [comment]
Thank you

**Pull request merged**
