### PR TITLE
First cut

### PR DESCRIPTION
**Pull request by vburckhardt**

### CODE REVIEW

**Comment by SirSpidey** [comment]
@vburckhardt I had some stuff in progress already, so I took some of this and included it in my PRs. The docs are now rendered at https://terraform-ibm-modules.github.io/documentation/ and we can iterate from there.

So I think we can close this and I'll document the diffs between your content and mine for you.

**Comment by vburckhardt** [comment]
@SirSpidey - Ok, here are some additional differences:
- local-dev-setup.md . The version in this PR is up to date (removing all internal/Goldeneye stuff)
- dev-maintenance.md. Take the one from this PR. It's been made up to date for external audience
- Under Reference -> remove Module inputs and Module outputs as they do not add anything specific to terraform ibm cloud modules (and contain some mistake / inaccuracies), and just explain some basic terraform concepts.
- Module authoring guidelines is the combination of the implementation guidelines and the design guidelines together.
- Testing your module -> use the tests.md from this PR. Also the link in implementation guideline links to this tests.md file (under module validation tests)
- Creating module documentation -> I had put a section on documentation under the implementation guidelines.
- Releasing versions -> I had addressed this under [Module versioning](https://terraform-ibm-modules.github.io/documentation/#/implementation_guidelines?id=module-versioning) in the implementation guidelines.

Also I was hoping to keep contribution commits from Albee's team (that's why I stated from pulling existing getting-started repo), but not sure if we can keep this with the structure

Wondering whether the github.io template adds something compared to just having README.md, etc Is it maybe a stepping stone to pushing within ibmcloud doc?

**Comment by SirSpidey** [comment]
@vburckhardt I'll definitely go through your content here to synch up. 

> Wondering whether the github.io template adds something compared to just having README.md, etc Is it maybe a stepping stone to pushing within ibmcloud doc?

Publishing to a site that's organized for documentation lends an air of professionalism to the content. In addition, the template adds full text search and navigation that's available all the time. And because it's still sourced in the repo, no one is precluded from reading the markdown directly from a clone if they want. From your question, I wonder if you think there's a down side.

> Also I was hoping to keep contribution commits from Albee's team (that's why I stated from pulling existing getting-started repo), but not sure if we can keep this with the structure

I've been operating from a "starting over" point of view. I don't see a lot of history in the getting-started commits that are critical as we move forward.

**Comment by vburckhardt** [comment]
@SirSpidey - Thanks

- Yes, just wanted to make sure you did not miss the other additions in this PR.
- On the a site/gh page, I'm open to trying to push as you have it, but here is what was behind my question:
   - For a consistency perspective, I'm feeling that we go against some established implicit practice across the OpenSource community on Github where where the documentation is directly visible in the github UI (from the README.md). Surfacing the modules documentations in README.md is also what we're doing with individual modules, so we would not be internally consistent between module documentation and the documentation repository. 
   - If we want to make this documentation more professional / official, we could use the docs.cloud.ibm.com to host it (and also align the styling there) 
- On the commit history - it is simply to keep credits to the original authors from https://github.com/terraform-ibm-modules/getting-started . But that said, given where we are now, I think we can have a credit list page somewhere in the documentation instead. Possibly this ties to crediting contribution in general, internal and external, so we could have a bigger holistic view on this topic.

**Comment by SirSpidey** [comment]
@vburckhardt I'm creating a PR to sync with the content changes in this PR.  Here are the diffs

### Slightly different content
- /README.md
    Don't want to have to update navigation in 2 places. We can continue to iterate on this readme.

---

### Updated source documentation source to match this PR
- local-dev-setup.md
- tests.md

---

### Only style or syntax diffs
- design_guidelines.md (renamed to design-guidelines.md)
- dev-maintenance.md 
- implementation_guidelines.md (renamed to implementation-guidelines.md)

---

### Different file names, same content
- issue_report_guidelines.md > support.md
- contribution_guidelines.md > contributing-module.md
- module_structure.md > module-structure.md

---

### Removed from doc source per request here

Note, though, that the files are In this PR as well
- input_variables.md
- output_values.md

---

### No content diffs
- issues.md
- metadata_schema.yaml
- module_structure.md
- terratest.md

**Comment by vburckhardt** [comment]
Incorporated into https://github.com/terraform-ibm-modules/documentation/pull/4

**Pull request closed without merging**
